### ISSUE TITLE
feat : 검색페이지 팔로우 api 추가

### ISSUE THREAD

**Issue by GBAJS754** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#140]
## 추가하려는 기능이 어떠한 문제 혹은 기능과 연관되어 있나요?
검색페이지 팔로우 api를 추가하고자 합니다.
## 원하는 기능 추가
- [ ] 검색페이지 팔로우 api 추가
- [ ] 검색 결과 레이아웃 수정

**Comment by DongjaJ** [comment]
요 이슈는 닫아도 되는건가요?
