### ISSUE TITLE
refactor: user 정보 저장 방법 context api에서 react query로 캐싱하도록 변경

### ISSUE THREAD

**Issue by DongjaJ** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#156]
## 추가하려는 기능이 어떠한 문제 혹은 기능과 연관되어 있나요?
- 현재 context api를 이용해서 user정보를 저장하고 있습니다.
- user 정보를 업데이트할때 약간의 시간이 걸리는데 이를 react query를 이용해서 캐싱하는 방식으로 변경하려고 합니다
## 원하는 기능 추가
- [ ] react query를 이용해 유저 정보를 캐싱

**Comment by GBAJS754** [comment]
굿
