### ISSUE TITLE
fix: 글상세, 글작성 다크모드에서 색상 오류 수정

### ISSUE THREAD

**Issue by colorkite10** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#180]
**버그 설명**
발생되는 문제에 대해 간단하게 설명해 주세요
글상세, 글작성 다크모드에서 색상 오류 수정이 필요합니다.

- 글 상세 페이지에서 다크모드로 변경 시 댓글 입력창의 텍스트 색깔이 보이지 않는 오류가 있습니다. 
- 글 작성 페이지에서 라이트 모드에서도 제목과 내용 입력 창의 배경색이 어둡게 보이는 오류가 있습니다. 

**버그 발생 단계**

**Comment by DongjaJ** [comment]
혹시 버그에 대해 자세히 설명해주실 수 있나요?

**Comment by colorkite10** [comment]
이슈 내용 자세하게 수정하였습니다!
