### ISSUE TITLE
refactor: 프로필 페이지 리팩토링

### ISSUE THREAD

**Issue by wukdddang** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#182]
## 개선해야 되는 코드 혹은 기능에 대해서 적어주세요
개선해야 될 코드에 대한 명확하고 간단한 설명

프로필 페이지 레이아웃 수정 작업이 필요합니다.

## 원하는 개선 방향
개선해야 되는 간단한 이유 혹은 개선 후 장점에 대해 적어주세요

- 프로핑 페이지에서 이미지를 클릭하면 이미지가 바로 수정되도록 처리해야합니다.

**Comment by DongjaJ** [comment]
여기서 수정 페이지에서 하는 작업은 제가 하고 있어요!
프로필 수정페이지에서 그럼 연필만 제거하고 사진은 그대로 있는건가요?

**Comment by wukdddang** [comment]
아, 사진도 없는편이 더 좋겠네요 ㅎㅎ 어제 회의때는 사진도 그냥 남겨두나보다 생각했는데 
리팩토링 후에는 이제 프로필 수정 페이지에서 사진을 수정하지는 않으니깐, 동환님 말씀하신대로 제거해도 좋을 것 같습니다!!
