### ISSUE TITLE
feat: API 데이터 모델 타입 추가

### ISSUE THREAD

**Issue by wukdddang** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#23]
## 추가하려는 기능이 어떠한 문제 혹은 기능과 연관되어 있나요?
- API에서 제공하는 데이터들의 모델 타입을 추가하려고 합니다.

## 원하는 기능 추가
추가하려는 기능을 명확하고 간결하게 설명해주세요
- [ ] User
- [ ] Channel
- [ ] Post
- [ ] Like
- [ ] Comment
- [ ] Notification
- [ ] Follow
- [ ] Conversation
- [ ] Message

## 생각 중인 기능 추가 방안
제시된 모델을 types폴더에 TS 파일로 추가하겠습니다.
## ETC
스크린샷이나 기능 등 추가 자료를 기술해 주세요

- ex1) types/Follow.ts
- ex2) types/Message.ts

**Comment by DongjaJ** [comment]
엇 이거 제가 회원가입 기능하면서 추가했어요!

**Comment by wukdddang** [comment]
와... 빛빛빛.... 넘 감사합니다 ㅎㅎㅎ 동환님 PR 먼저 확인할걸 그랬군요 ㅠㅠ ㅎㅎㅎ
다시한번 감사합니다!! 🙇🏻‍♂️🙇🏻‍♂️

**Comment by wukdddang** [comment]
와... 빛빛빛.... 넘 감사합니다 ㅎㅎㅎ 동환님 PR 먼저 확인할걸 그랬군요 ㅠㅠ ㅎㅎㅎ
다시한번 감사합니다!! 🙇🏻‍♂️🙇🏻‍♂️
