### ISSUE TITLE
feat: 홈페이지 배너 추가

### ISSUE THREAD

**Issue by khakhiD** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#241]
## 추가하려는 기능이 어떠한 문제 혹은 기능과 연관되어 있나요?
문제가 무엇인지에 대한 명확하고 간결한 설명을 적어주세요

## 원하는 기능 추가
추가하려는 기능을 명확하고 간결하게 설명해주세요
- [ ] 배너 추가
- [ ] daisy ui carousel 컴포넌트 활용해보기

## 생각 중인 기능 추가 방안
해결책으로 간단하게 생각한 기능의 방향 혹은 컴포넌트를 설명해주세요
## ETC
스크린샷이나 기능 등 추가 자료를 기술해 주세요
![image](https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/74141521/7d1ab6b5-0bfe-47ed-8850-e02404a2c616)

**Comment by GBAJS754** [comment]
혹시 뜨거운 뉴스에 불표시 동호님이 빼신걸까요??
