### ISSUE TITLE
fix : 프로필 페이지 url로 이동할시 에러

### ISSUE THREAD

**Issue by GBAJS754** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#277]
**개선해야 되는 코드 혹은 기능에 대해서 적어주세요**
로그인한 상태에서 프로필 페이지 url로 이동을 하면 에러(?)가 뜸
**원하는 개선 방향**
개선해야 되는 간단한 이유 혹은 개선 후 장점에 대해 적어주세요
**생각 중인 기능 추가 방안**
해결책으로 간단하게 생각한 개선 방법에 대해 적어주세요
**ETC**

https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/104294861/bab597ce-41f5-4b71-a80c-efe302fbe7a9

**Comment by DongjaJ** [comment]
서버에서 502에러가 터지는 것을 보니 에러 처리가 제대로 안되는 것 같습니다.. 추후에 errorBoundary 설정시 봐야할 것 같아 일단은 닫아두겠습니다
