### ISSUE TITLE
fix: Article 공통 컴포넌트 storybook 에러

### ISSUE THREAD

**Issue by colorkite10** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#82]
**버그 설명**
Article 공통 컴포넌트의 storybook에서 `useNavigate() may be used only in the context of a <Router> component.`와 같은 에러가 발생합니다. 

![image](https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/98521882/f7b5afa1-4e68-4a8c-9edf-84f102b8b005)

**버그 발생 단계**
동작을 재현하는 단계:
1. storybook 에서 Article

**Comment by jung-han** [comment]
storybook-addon-react-router-v6
한번 찾아보시고 팀원들한테 어떤 용도인지 공유해주세여~
