### ISSUE TITLE
design: Toast 공통 컴포넌트 추가

### ISSUE THREAD

**Issue by khakhiD** [prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF#84]
## 추가하려는 기능이 어떠한 문제 혹은 기능과 연관되어 있나요?
문제가 무엇인지에 대한 명확하고 간결한 설명을 적어주세요
## 원하는 기능 추가
daisy UI를 활용한 토스트 메시지 공통 컴포넌트 개발하기
- [ ] daisy ui 컴포넌트 사용
- [ ] 프로젝트 전체 스타일과 결을 맞춰서 커스텀하기

## 생각 중인 기능 추가 방안
해결책으로 간단하게 생각한 기능의 방향 혹은 컴포넌트를 설명해주세요
## ETC
스크린샷이나 기능 등 추가 자료를 기술해 주세요

![image](https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/74141521/04a42fee-3e04-4742-978e-9334ffd5ffa8)

**Comment by GBAJS754** [comment]
알림 페이지에 쓰이는건가용??

**Comment by DongjaJ** [comment]
제 생각에는 알림 페이지보다는 유저의 액션에 대한 알림인 것 같아요!
ex) 로그인 성공, 게시글 등록, 삭제 등등
